### ISSUE TITLE
Nexus Mods fetching seems to be broken

### ISSUE THREAD

**Issue by chief-turkler** [wispborne/StarsectorModRepo#1]
![image](https://user-images.githubusercontent.com/49252967/217725562-48e090c2-91b4-4848-9316-c603eaf99457.png)

none of the mods listed here appear on the starmodder database. old ones like galaxy tiger do seem to appear correctly however.

**Comment by wispborne** [comment]
```
2023-02-08T19:03:12Z [DefaultDispatcher-worker-6] W/NexusReader.readAllMessages/ java.util.concurrent.CancellationException: Timed out waiting for 180000 ms
	at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:97)
	at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:95)

```

Looks like Nexus didn't respond, or something. 
I'll have it try again, but I just noticed that it's taking over an hour to merge mods that are found in multiple places, whereas it used to take less than 10 minutes, so I need to look into that first.

**Comment by wispborne** [comment]
Not fixing this, the content on Nexus isn't worth the effort.
